/**
 * Parity test: the TypeScript router must agree with the Python reference.
 *
 * pipeline/travel.py is the authority for the cost model and
 * pipeline/07_validate_routing.py pins it to canon. This port is the thing that
 * actually runs in the browser, so it has to produce the same answers. Any
 * divergence means one of the two drifted.
 *
 * Run: npm run test:parity
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

import { TerrainGrid, buildModes } from '../src/lib/router'
import type { Place, TerrainMeta, TravelConfig } from '../src/lib/types'
import { isFailure } from '../src/lib/types'

const here = dirname(fileURLToPath(import.meta.url))
const DATA = resolve(here, '../public/data')

const read = <T>(name: string): T => JSON.parse(readFileSync(resolve(DATA, name), 'utf8')) as T

const meta = read<TerrainMeta>('terrain.json')
const bin = new Uint8Array(readFileSync(resolve(DATA, 'terrain.bin')))
const gazetteer = read<Place[]>('gazetteer.json')
const travel = read<TravelConfig>('travel-modes.json')

const grid = new TerrainGrid(meta, bin)
const modes = buildModes(travel)
const places = new Map(gazetteer.map((p) => [p.name, p]))

interface Fixture {
  from: string
  to: string
  mode: string
  miles: number
  days: number
  pathPoints: number
  straightLine: boolean
}

// Generated by pipeline/07_validate_routing.py — never hand-edited, so a change
// to the cost model shows up here as a real diff rather than a stale constant.
const fixtures = read<{ routes: Fixture[]; blocked: Array<Omit<Fixture, 'miles' | 'days' | 'pathPoints' | 'straightLine'>> }>(
  'route-fixtures.json',
)

const TOLERANCE = 0.001 // the two implementations should agree to rounding

let failures = 0
const pad = (s: string, n: number) => s.padEnd(n)

console.log(`  grid ${grid.width}x${grid.height}, ${grid.milesPerDegree} miles/degree\n`)
console.log(`  ${pad('journey', 42)}${pad('mode', 10)}${'miles'.padStart(8)}${'days'.padStart(8)}   vs python`)

for (const fx of fixtures.routes) {
  const a = places.get(fx.from)
  const b = places.get(fx.to)
  const label = `${fx.from} -> ${fx.to}`
  if (!a || !b) {
    console.log(`  ${pad(label, 42)}${pad(fx.mode, 10)}  MISSING PLACE`)
    failures++
    continue
  }
  const r = grid.route(modes[fx.mode], [a.lon, a.lat], [b.lon, b.lat])
  if (isFailure(r)) {
    console.log(`  ${pad(label, 42)}${pad(fx.mode, 10)}  ${r.message}`)
    failures++
    continue
  }
  const dMiles = Math.abs(r.miles - fx.miles) / fx.miles
  const dDays = Math.abs(r.days - fx.days) / fx.days
  const ok = dMiles <= TOLERANCE && dDays <= TOLERANCE
  if (!ok) failures++
  console.log(
    `  ${pad(label, 42)}${pad(fx.mode, 10)}${r.miles.toFixed(0).padStart(8)}` +
    `${r.days.toFixed(2).padStart(8)}   ${fx.miles.toFixed(0)}/${fx.days.toFixed(2)} ` +
    `${ok ? 'ok' : '<-- DIVERGED'}`,
  )
}

console.log()
for (const fx of fixtures.blocked) {
  const a = places.get(fx.from)!
  const b = places.get(fx.to)!
  const r = grid.route(modes[fx.mode], [a.lon, a.lat], [b.lon, b.lat])
  const blocked = isFailure(r)
  if (!blocked) failures++
  console.log(`  ${pad(`${fx.from} -> ${fx.to} (${fx.mode})`, 52)}` +
    `${blocked ? 'blocked, as expected' : '<-- SHOULD BE BLOCKED'}`)
}

// performance: routing runs on the UI thread, so it has to stay interactive
const kl = places.get("King's Landing")!
const wf = places.get('Winterfell')!
const t0 = performance.now()
const RUNS = 20
for (let i = 0; i < RUNS; i++) grid.route(modes.horse, [kl.lon, kl.lat], [wf.lon, wf.lat])
const perRun = (performance.now() - t0) / RUNS
console.log(`\n  King's Landing -> Winterfell: ${perRun.toFixed(1)}ms per query`)
if (perRun > 250) {
  console.log('  <-- too slow to run on the UI thread; move routing to a worker')
  failures++
}

if (failures) {
  console.error(`\n  ${failures} failure(s) — the TS port has drifted from pipeline/travel.py`)
  process.exit(1)
}
console.log('\n  TypeScript router matches the Python reference')
